language: generic

# conditional build
conditions: v1

# build only the following:
#   master branch
#   branches starting with `ci-` or `ci/`
#   commits with `[build pdf]` in the commit message
if: branch == master || branch =~ ^(?i:ci)(-|\/).* || commit_message =~ /^.*\[build pdf\].*$/

# install texlive for using pdflatex and biber in the build
install:
- source ./bin/install_texlive.sh

# cache the texlive installation and all installed packages
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"

# run the PDF build-steps (pdflatex and biber) for
# main file: paper.tex
# output filename: dODo-paper.pdf
script:
- "./bin/build.sh paper dODo-paper.pdf"

# use deployment to push back the resulting PDF into the corresponding branch
deploy:
  skip_cleanup: true
  provider: script
  script: "./bin/travis-push.sh dODo-paper.pdf"
  on:
    all_branches: true

# secure GH_TOKEN for Github API authentication
env:
  global:
    secure: "nPqjr07DkyC+pMQAP7jFUfHt7L7Bf+PxpHyKIcmVh/W14E4LiZWgDMxxTDCAkyo40RCFlx3RBRR3mRx7HU4OLKW/AoxOUq2ZmSx7z5tlM8VUe++DlcOyKw2SaWyxG69u/IXpKmPlcj5Uq+/mF5ibhhkRcIoDsYJKBubP22qGy9lxKeP6q+gldCmjU74N7XambI6IWgbUiZiYpiCi14mzG1/JMtzeK44Tpn1H0HfngahQsUXczfmhzLi59MPyM2aH3tuJlTyzcdxRW2fjbKsb54pWutmbWiG+FjlNV+TAny1zdstic+NKvaWJ9Ud3RhLQYFBalZqVHZ1MdCkHB29SZn3MQMkGCy9vHVT4FonP3Rk40978Slz0MBNy1L/IzdnBsL2lSP8xRAZGH9a4bfKVqGw9gZ1HoIsBVxytsq1/vPUJaK332X2HOv/ejQqMWTB4CpTgD5p+pc7Rs/rvhC1rJvj7W/jpf4pgf543QiTWmtAo/3PNhSymiBHyHh44YBGXvlCb+2EF3KA0GaHbQ+7vcfqqgPRO9BoJVdS7Mr38/2ECLW+BaZa3VQnzQ6/mRBup4eOY8Vp5aDo62LaiSKf0N1dfN5Z4hwCF1fcfal6MG41O8Mu0GJXCw9XZ57/qLurQd8aPaX5YiH12+TFRDMahsuB2zHPVvB3advgltknuHY8="
